vim.keymap.set('n', '<leader>b1', '<Cmd>BufferGoto 1<CR>')
vim.keymap.set('n', '<leader>b2', '<Cmd>BufferGoto 2<CR>')
vim.keymap.set('n', '<leader>b3', '<Cmd>BufferGoto 3<CR>')
vim.keymap.set('n', '<leader>b4', '<Cmd>BufferGoto 4<CR>')
vim.keymap.set('n', '<leader>b5', '<Cmd>BufferGoto 5<CR>')
vim.keymap.set('n', '<leader>b6', '<Cmd>BufferGoto 6<CR>')
vim.keymap.set('n', '<leader>b7', '<Cmd>BufferGoto 7<CR>')
vim.keymap.set('n', '<leader>b8', '<Cmd>BufferGoto 8<CR>')
vim.keymap.set('n', '<leader>b9', '<Cmd>BufferGoto 9<CR>')
vim.keymap.set('n', '<leader>bp', '<Cmd>BufferPrevious<CR>')
vim.keymap.set('n', '<leader>bn', '<Cmd>BufferNext<CR>')
vim.keymap.set('n', '<leader>bf', '<Cmd>BufferFirst<CR>')
vim.keymap.set('n', '<leader>bl', '<Cmd>BufferLast<CR>')
vim.keymap.set("n", "<leader>bc", "<Cmd>BufferClose<CR>");
