local codicon_symbol = {
	Text = "",
	Method = "",
	Function = "",
	Constructor = "",
	Field = "",
	Variable = "",
	Class = "",
	Interface = "",
	Module = "",
	Property = "",
	Unit = "",
	Value = "",
	Enum = "",
	Keyword = "",
	Snippet = "",
	Color = "",
	File = "",
	Reference = "",
	Folder = "",
	EnumMember = "",
	Constant = "",
	Struct = "",
	Event = "",
	Operator = "",
	TypeParameter = "",
}

local oct_symbol = {
	Text = "󰦨",
	Method = "󰡱",
	Function = "󰡱",
	Constructor = "󰡱",
	Field = "󱄑",
	Variable = "󰫧",
	Class = "",
	Interface = "",
	Module = "󰏗",
	Property = "󰌋",
	Unit = "󰑭",
	Value = "󰎠",
	Enum = "",
	Keyword = "",
	Snippet = "",
	Color = "",
	File = "",
	Reference = "",
	Folder = "",
	EnumMember = "",
	Constant = "",
	Struct = "",
	Event = "",
	Operator = "",
	TypeParameter = "",
}
return {
	"onsails/lspkind.nvim",
	config = function()
		require("lspkind").setup({
			symbol_map = codicon_symbol,
		})
	end,
}
